
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 01 08:53:56 VET 2013
//----------------------------------------------------

package Sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Y = 19;
  public static final int MULT = 29;
  public static final int PROGRAMA = 2;
  public static final int SI = 32;
  public static final int MIRAR_IZQ = 12;
  public static final int DIFERENTE = 26;
  public static final int O = 20;
  public static final int RESTA = 28;
  public static final int INT = 15;
  public static final int COR_CIERRA = 6;
  public static final int PARENT_CIERRA = 9;
  public static final int HASTA = 37;
  public static final int AVANZAR = 14;
  public static final int IGUAL = 25;
  public static final int COR_ABRE = 5;
  public static final int SINO = 35;
  public static final int BOOL = 16;
  public static final int DIV = 30;
  public static final int NUM = 38;
  public static final int SUMA = 27;
  public static final int IGUAL_LOGICO = 42;
  public static final int PUNTO_COMA = 7;
  public static final int ID = 18;
  public static final int EOF = 0;
  public static final int TRUE = 39;
  public static final int error = 1;
  public static final int COMA = 17;
  public static final int MENOR = 21;
  public static final int MIRAR_DER = 13;
  public static final int MOD = 31;
  public static final int LLAVE_ABRE = 3;
  public static final int MAYOR = 23;
  public static final int ENDIF = 34;
  public static final int REPITA = 36;
  public static final int MAYOR_IGUAL = 24;
  public static final int THEN = 33;
  public static final int MIRAR_ABAJO = 11;
  public static final int MIRAR_ARRIBA = 10;
  public static final int PARA = 41;
  public static final int PARENT_ABRE = 8;
  public static final int LLAVE_CIERRA = 4;
  public static final int MENOR_IGUAL = 22;
  public static final int FALSE = 40;
}

